import { Router } from "express";
import { register, login, verifyOtp, resendOtp, refresh, getMe, forgotPassword, resetPassword } from "../controllers/auth.controller";
import { authenticate } from "../middleware/auth";
const router = Router();
router.post("/register",        register);
router.post("/login",           login);
router.post("/verify-otp",      verifyOtp);
router.post("/resend-otp",      resendOtp);
router.post("/refresh",         refresh);
router.get("/me",               authenticate, getMe);
router.post("/forgot-password", forgotPassword);
router.post("/reset-password",  resetPassword);
export default router;
